import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  return (
    <>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.logoBox}>
            <img
              className={styles.logoImage}
              src="https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg"
            ></img>
            <p className={styles.sideText}>
              Facebook helps you connect and share with the people in your life.
            </p>
          </div>
          <div className={styles.formBox}>
            <div className={styles.formWhiteBox}>
              <input
                className={styles.formInput}
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="Email address or phone number"
              />
              <input
                className={styles.formInput}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Password"
                type={"password"}
              />
              <button className={styles.loginButton}>Log in</button>
              <p className={styles.forgetPassword}>Forgotten password?</p>
              <div className={styles.dividerBox}></div>
              <button className={styles.createButton}>
                Create New Account
              </button>
            </div>
            <p style={{ fontFamily: "helvetica", marginTop: "20px" }}>
              <strong> Create a Page</strong> for a celebrity, brand or
              business.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
